-- MySQL Script generated by MySQL Workbench
-- Thu Mar 23 01:57:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Caso2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Caso2` ;

-- -----------------------------------------------------
-- Schema Caso2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Caso2` DEFAULT CHARACTER SET utf8 ;
USE `Caso2` ;

-- -----------------------------------------------------
-- Table `Caso2`.`Copero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Copero` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Copero` (
  `idCopero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `telefono` INT UNSIGNED NOT NULL,
  `cedula` VARCHAR(20) NOT NULL,
  `cuentaBancaria` VARCHAR(22) NOT NULL,
  `totalDinero` DECIMAL(11,2) NOT NULL DEFAULT 0,
  `fechaUltimoPago` DATETIME NOT NULL,
  `deleted` BIT NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  PRIMARY KEY (`idCopero`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`PagosCoperos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`PagosCoperos` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`PagosCoperos` (
  `idPagoCopero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `fechaPago` DATETIME NOT NULL,
  `idCopero` INT UNSIGNED NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  PRIMARY KEY (`idPagoCopero`, `idCopero`),
  INDEX `fk_PagosCoperos_Copero1_idx` (`idCopero` ASC) VISIBLE,
  CONSTRAINT `fk_PagosCoperos_Copero1`
    FOREIGN KEY (`idCopero`)
    REFERENCES `Caso2`.`Copero` (`idCopero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Carrito` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Carrito` (
  `idCarrito` SMALLINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(10) NOT NULL,
  `enabled` BIT NOT NULL,
  PRIMARY KEY (`idCarrito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Playas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Playas` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Playas` (
  `idPlaya` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idPlaya`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`ComisionesLogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`ComisionesLogs` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`ComisionesLogs` (
  `idComisionLog` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `porcentaje` DECIMAL(5,2) NOT NULL,
  `enabled` BIT NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFinal` DATETIME NULL,
  PRIMARY KEY (`idComisionLog`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Ventas` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Ventas` (
  `idVenta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPlaya` SMALLINT UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL,
  `idComisionLog` INT UNSIGNED NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  `idCopero` INT UNSIGNED NOT NULL,
  `deleted` BIT NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  `pago` DECIMAL(10,2) NOT NULL,
  `vuelto` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idVenta`, `idPlaya`, `idComisionLog`, `idCopero`),
  INDEX `fk_Ventas_Playas1_idx` (`idPlaya` ASC) VISIBLE,
  INDEX `fk_Ventas_Comisiones1_idx` (`idComisionLog` ASC) VISIBLE,
  INDEX `fk_Ventas_Copero1_idx` (`idCopero` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Playas1`
    FOREIGN KEY (`idPlaya`)
    REFERENCES `Caso2`.`Playas` (`idPlaya`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Comisiones1`
    FOREIGN KEY (`idComisionLog`)
    REFERENCES `Caso2`.`ComisionesLogs` (`idComisionLog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Copero1`
    FOREIGN KEY (`idCopero`)
    REFERENCES `Caso2`.`Copero` (`idCopero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Caso2`.`UnidadesMedida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`UnidadesMedida` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`UnidadesMedida` (
  `idUnidadeMedida` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idUnidadeMedida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Ingredientes` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Ingredientes` (
  `idIngrediente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `idUnidadeMedida` TINYINT UNSIGNED NOT NULL,
  `enabled` BIT NOT NULL,
  `precio` DECIMAL(8,2) NOT NULL,
  `fechaCompra` DATETIME NOT NULL,
  PRIMARY KEY (`idIngrediente`),
  INDEX `fk_Ingredientes_UnidadesMedida1_idx` (`idUnidadeMedida` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredientes_UnidadesMedida1`
    FOREIGN KEY (`idUnidadeMedida`)
    REFERENCES `Caso2`.`UnidadesMedida` (`idUnidadeMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Turnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Turnos` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Turnos` (
  `idTurno` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `horaInicio` TIME NOT NULL,
  `horaFinal` TIME NOT NULL,
  PRIMARY KEY (`idTurno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Reportes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Reportes` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Reportes` (
  `idReporte` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idCopero` INT UNSIGNED NOT NULL,
  `idCarrito` SMALLINT(4) UNSIGNED NOT NULL,
  `idTurno` SMALLINT UNSIGNED NOT NULL,
  `fecha` DATE NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  PRIMARY KEY (`idReporte`),
  INDEX `fk_Reportes_Copero1_idx` (`idCopero` ASC) VISIBLE,
  INDEX `fk_Reportes_Carrito1_idx` (`idCarrito` ASC) VISIBLE,
  INDEX `fk_Reportes_Turnos1_idx` (`idTurno` ASC) VISIBLE,
  CONSTRAINT `fk_Reportes_Copero1`
    FOREIGN KEY (`idCopero`)
    REFERENCES `Caso2`.`Copero` (`idCopero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reportes_Carrito1`
    FOREIGN KEY (`idCarrito`)
    REFERENCES `Caso2`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reportes_Turnos1`
    FOREIGN KEY (`idTurno`)
    REFERENCES `Caso2`.`Turnos` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Productos` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Productos` (
  `idProducto` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  `enabled` BIT NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`IngredientesXproductos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`IngredientesXproductos` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`IngredientesXproductos` (
  `idIngrediente` INT UNSIGNED NOT NULL,
  `idProducto` SMALLINT UNSIGNED NOT NULL,
  `cantidad` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`idIngrediente`, `idProducto`),
  INDEX `fk_Ingredientes_has_Productos_Productos1_idx` (`idProducto` ASC) VISIBLE,
  INDEX `fk_Ingredientes_has_Productos_Ingredientes1_idx` (`idIngrediente` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredientes_has_Productos_Ingredientes1`
    FOREIGN KEY (`idIngrediente`)
    REFERENCES `Caso2`.`Ingredientes` (`idIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredientes_has_Productos_Productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Caso2`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`InventarioCarrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`InventarioCarrito` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`InventarioCarrito` (
  `idIngrediente` INT UNSIGNED NOT NULL,
  `idCarrito` SMALLINT(4) UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT NOW(),
  `checkSum` VARBINARY(150) NOT NULL,
  `cantidad` DECIMAL(10,4) NOT NULL,
  `idCoperoResponsable` INT UNSIGNED NOT NULL,
  `tipoOperacion` TINYINT UNSIGNED NOT NULL COMMENT '0 = Producto Nuevo\n1 = Venta\n2 = Refill\n3= Producto Caducado\n',
  PRIMARY KEY (`idIngrediente`, `idCarrito`, `idCoperoResponsable`),
  INDEX `fk_Ingredientes_has_Carrito_Carrito1_idx` (`idCarrito` ASC) VISIBLE,
  INDEX `fk_Ingredientes_has_Carrito_Ingredientes1_idx` (`idIngrediente` ASC) VISIBLE,
  INDEX `fk_InventarioCarrito_Copero1_idx` (`idCoperoResponsable` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredientes_has_Carrito_Ingredientes1`
    FOREIGN KEY (`idIngrediente`)
    REFERENCES `Caso2`.`Ingredientes` (`idIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredientes_has_Carrito_Carrito1`
    FOREIGN KEY (`idCarrito`)
    REFERENCES `Caso2`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InventarioCarrito_Copero1`
    FOREIGN KEY (`idCoperoResponsable`)
    REFERENCES `Caso2`.`Copero` (`idCopero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`ProductosXventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`ProductosXventas` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`ProductosXventas` (
  `idProducto` SMALLINT UNSIGNED NOT NULL,
  `idVenta` INT UNSIGNED NOT NULL,
  `cantidad` SMALLINT ZEROFILL NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  PRIMARY KEY (`idProducto`, `idVenta`),
  INDEX `fk_Productos_has_Ventas_Ventas1_idx` (`idVenta` ASC) VISIBLE,
  INDEX `fk_Productos_has_Ventas_Productos1_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_has_Ventas_Productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Caso2`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Ventas_Ventas1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `Caso2`.`Ventas` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Clientes` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `createdAT` DATETIME NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`SolicitudesWeb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`SolicitudesWeb` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`SolicitudesWeb` (
  `idSolicitudWeb` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idCliente` INT UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL,
  `ubicacion` POINT NOT NULL,
  `señasDireccion` VARCHAR(500) NULL,
  `idPlaya` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idSolicitudWeb`, `idCliente`, `idPlaya`),
  INDEX `fk_SolicitudesWeb_Clientes1_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_SolicitudesWeb_Playas1_idx` (`idPlaya` ASC) VISIBLE,
  CONSTRAINT `fk_SolicitudesWeb_Clientes1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Caso2`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolicitudesWeb_Playas1`
    FOREIGN KEY (`idPlaya`)
    REFERENCES `Caso2`.`Playas` (`idPlaya`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`ProductosXSolicitudesWeb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`ProductosXSolicitudesWeb` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`ProductosXSolicitudesWeb` (
  `idProducto` SMALLINT UNSIGNED NOT NULL,
  `cantidad` DECIMAL(8,2) NOT NULL,
  `idSolicitudWeb` INT UNSIGNED NOT NULL,
  `comentario` VARCHAR(500) NULL,
  PRIMARY KEY (`idProducto`, `idSolicitudWeb`),
  INDEX `fk_Productos_has_SolicitudesWeb_Productos1_idx` (`idProducto` ASC) VISIBLE,
  INDEX `fk_ProductosXSolicitudesWeb_SolicitudesWeb1_idx` (`idSolicitudWeb` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_has_SolicitudesWeb_Productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Caso2`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductosXSolicitudesWeb_SolicitudesWeb1`
    FOREIGN KEY (`idSolicitudWeb`)
    REFERENCES `Caso2`.`SolicitudesWeb` (`idSolicitudWeb`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`LogPrecios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`LogPrecios` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`LogPrecios` (
  `idLogPrecio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(9,2) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFinal` DATETIME NULL,
  `active` BIT NOT NULL,
  `createdAT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `checkSum` VARBINARY(150) NOT NULL,
  `idProducto` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idLogPrecio`, `idProducto`),
  INDEX `fk_LogPrecios_Productos1_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_LogPrecios_Productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Caso2`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`PrecioProductoXplaya`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`PrecioProductoXplaya` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`PrecioProductoXplaya` (
  `idPrecioProductoXplaya` INT UNSIGNED NOT NULL,
  `idPlaya` SMALLINT UNSIGNED NOT NULL,
  `idProducto` SMALLINT UNSIGNED NOT NULL,
  `valor` DECIMAL(9,2) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFinal` DATETIME NULL,
  `active` BIT NOT NULL,
  `createdAT` TIMESTAMP NOT NULL,
  `updatedAT` TIMESTAMP NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  PRIMARY KEY (`idPrecioProductoXplaya`, `idPlaya`, `idProducto`),
  INDEX `fk_Playas_has_LogPrecios_Playas1_idx` (`idPlaya` ASC) VISIBLE,
  INDEX `fk_PrecioProductoXplaya_Productos1_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Playas_has_LogPrecios_Playas1`
    FOREIGN KEY (`idPlaya`)
    REFERENCES `Caso2`.`Playas` (`idPlaya`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PrecioProductoXplaya_Productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Caso2`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB


-- -----------------------------------------------------
-- Table `Caso2`.`ReportesXcajas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`ReportesXcajas` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`ReportesXcajas` (
  `idCajaDineroLog` INT UNSIGNED NOT NULL,
  `idReporte` INT UNSIGNED NOT NULL,
  `idCoperoRecibe` INT UNSIGNED NOT NULL,
  `isAgree` BIT NOT NULL,
  `dinero` DECIMAL(11,2) NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  PRIMARY KEY (`idCajaDineroLog`, `idReporte`, `idCoperoRecibe`),
  INDEX `fk_CajaDineroLogs_has_Reportes_Reportes1_idx` (`idReporte` ASC) VISIBLE,
  INDEX `fk_ReportesXcajas_Copero1_idx` (`idCoperoRecibe` ASC) VISIBLE,
  CONSTRAINT `fk_CajaDineroLogs_has_Reportes_Reportes1`
    FOREIGN KEY (`idReporte`)
    REFERENCES `Caso2`.`Reportes` (`idReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReportesXcajas_Copero1`
    FOREIGN KEY (`idCoperoRecibe`)
    REFERENCES `Caso2`.`Copero` (`idCopero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`EstadoSolicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`EstadoSolicitud` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`EstadoSolicitud` (
  `idEstadoSolicitud` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEstadoSolicitud`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`SolicitudesLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`SolicitudesLog` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`SolicitudesLog` (
  `idEstadoSolicitud` INT UNSIGNED NOT NULL,
  `idSolicitudWeb` INT UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  PRIMARY KEY (`idEstadoSolicitud`, `idSolicitudWeb`),
  INDEX `fk_EstadoSolicitud_has_SolicitudesWeb_SolicitudesWeb1_idx` (`idSolicitudWeb` ASC) VISIBLE,
  INDEX `fk_EstadoSolicitud_has_SolicitudesWeb_EstadoSolicitud1_idx` (`idEstadoSolicitud` ASC) VISIBLE,
  CONSTRAINT `fk_EstadoSolicitud_has_SolicitudesWeb_EstadoSolicitud1`
    FOREIGN KEY (`idEstadoSolicitud`)
    REFERENCES `Caso2`.`EstadoSolicitud` (`idEstadoSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EstadoSolicitud_has_SolicitudesWeb_SolicitudesWeb1`
    FOREIGN KEY (`idSolicitudWeb`)
    REFERENCES `Caso2`.`SolicitudesWeb` (`idSolicitudWeb`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`TipoOperacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`TipoOperacion` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`TipoOperacion` (
  `idTipoOperacion` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idTipoOperacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`TipoEvento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`TipoEvento` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`TipoEvento` (
  `idTipoEvento` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Sources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Sources` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Sources` (
  `idSource` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idSource`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Levels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Levels` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Levels` (
  `idLevel` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idLevel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Bitacora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Bitacora` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Bitacora` (
  `idBitacora` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user` VARCHAR(40) NOT NULL,
  `idTipoOperacion` SMALLINT UNSIGNED NOT NULL,
  `idTipoEvento` SMALLINT UNSIGNED NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  `idSource` SMALLINT UNSIGNED NOT NULL,
  `idLevel` TINYINT UNSIGNED NOT NULL,
  `computer` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `referenceid1` BIGINT NOT NULL,
  `referenceid2` BIGINT NULL,
  `value1` VARCHAR(60) NOT NULL,
  `value2` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idBitacora`, `idTipoOperacion`, `idTipoEvento`, `idSource`, `idLevel`),
  INDEX `fk_Bitacora_TipoOperacion1_idx` (`idTipoOperacion` ASC) VISIBLE,
  INDEX `fk_Bitacora_TipoEvento1_idx` (`idTipoEvento` ASC) VISIBLE,
  INDEX `fk_Bitacora_Sources1_idx` (`idSource` ASC) VISIBLE,
  INDEX `fk_Bitacora_Levels1_idx` (`idLevel` ASC) VISIBLE,
  CONSTRAINT `fk_Bitacora_TipoOperacion1`
    FOREIGN KEY (`idTipoOperacion`)
    REFERENCES `Caso2`.`TipoOperacion` (`idTipoOperacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bitacora_TipoEvento1`
    FOREIGN KEY (`idTipoEvento`)
    REFERENCES `Caso2`.`TipoEvento` (`idTipoEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bitacora_Sources1`
    FOREIGN KEY (`idSource`)
    REFERENCES `Caso2`.`Sources` (`idSource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bitacora_Levels1`
    FOREIGN KEY (`idLevel`)
    REFERENCES `Caso2`.`Levels` (`idLevel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



set @fechaInicial = '2022-01-01 09:00:00';

INSERT INTO Playas (nombre) VALUES
('Ocotal'),
('Matapalito'),
('Guacamaya');

INSERT INTO carrito (color, enabled) VALUES
('#FA370D', 1),
('#F79510', 1),
('#84F709', 1),
('#5AF035', 1),
('#1EF73C', 1),
('#10F880', 1),
('#10F8D5', 1),
('#10C7F8', 1),
('#1068F8', 1),
('#32496E', 1),
('#1F2FF7', 1),
('#9E0AFE', 1),
('#C108D7', 1),
('#FC05AD', 1),
('#F55BA1', 1);


insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Jeannine","Spivey",42995444,"709680253","CR84614233647678488716",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Jeannine","Spivey","42995444","709680253","CR84614233647678488716", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Jaime","Mchenry",47161441,"304530517","CR39375877895213729418",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Jaime","Mchenry","47161441","304530517","CR39375877895213729418", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Bettina","Reynolds",21125967,"405310629","CR08013612496731726304",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Bettina","Reynolds","21125967","405310629","CR08013612496731726304", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Jeffrey","Fane",25555620,"704520866","CR12116602002342431509",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Jeffrey","Fane","25555620","704520866","CR12116602002342431509", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Patrick","Caldwell",22628645,"709030144","CR74560783342674759696",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Patrick","Caldwell","22628645","709030144","CR74560783342674759696", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Michael","Bailey",38315480,"405810233","CR01647191048230951046",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Michael","Bailey","38315480","405810233","CR01647191048230951046", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Barbara","Walker",61651376,"700130633","CR06362019088083487631",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Barbara","Walker","61651376","700130633","CR06362019088083487631", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("John","Ko",32343895,"708490194","CR19796149127277806961",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("John","Ko","32343895","708490194","CR19796149127277806961", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Michael","Yale",60345808,"501180673","CR67164209421532038988",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Michael","Yale","60345808","501180673","CR67164209421532038988", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Janet","Moore",65715641,"506980801","CR78940535412545882963",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Janet","Moore","65715641","506980801","CR78940535412545882963", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("James","Battle",41109325,"604330161","CR51088563266483879087",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("James","Battle","41109325","604330161","CR51088563266483879087", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Carlo","Love",45212350,"701960822","CR96712915376463124794",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Carlo","Love","45212350","701960822","CR96712915376463124794", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Pablo","Torres",17356659,"307820572","CR99099017904692661727",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Pablo","Torres","17356659","307820572","CR99099017904692661727", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Regina","Finch",71661935,"104260152","CR31570797713236708360",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Regina","Finch","71661935","104260152","CR31570797713236708360", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Patricia","Ayres",83026587,"200880596","CR96216982921245394360",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Patricia","Ayres","83026587","200880596","CR96216982921245394360", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Jean","Tucker",19275111,"101760761","CR37565531585108919195",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Jean","Tucker","19275111","101760761","CR37565531585108919195", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Justin","Paschall",72177063,"600300172","CR29731002676688357189",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Justin","Paschall","72177063","600300172","CR29731002676688357189", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Clifford","Stringer",63113290,"402840450","CR52427705272585508860",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Clifford","Stringer","63113290","402840450","CR52427705272585508860", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Margaret","Harvey",86092011,"103820679","CR89693391871984036759",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Margaret","Harvey","86092011","103820679","CR89693391871984036759", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("William","Joseph",54159139,"505460939","CR55456630374555487372",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("William","Joseph","54159139","505460939","CR55456630374555487372", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Robert","Johnson",42804436,"600630121","CR33090729864277013853",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Robert","Johnson","42804436","600630121","CR33090729864277013853", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Amanda","Morales",81592129,"202480718","CR59763912571149560120",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Amanda","Morales","81592129","202480718","CR59763912571149560120", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Mary","Varnell",27476957,"100340927","CR93209881192688787449",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Mary","Varnell","27476957","100340927","CR93209881192688787449", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Mark","Hull",49836131,"208770439","CR58700914433301602729",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Mark","Hull","49836131","208770439","CR58700914433301602729", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Samuel","Wehner",70936996,"209780997","CR13693514061588224697",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Samuel","Wehner","70936996","209780997","CR13693514061588224697", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Destiny","Escobar",12322724,"402390488","CR79212687941696968992",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Destiny","Escobar","12322724","402390488","CR79212687941696968992", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Robert","Desimone",65355775,"404200402","CR34118289571360984596",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Robert","Desimone","65355775","404200402","CR34118289571360984596", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Antonio","Sabo",68433302,"207920609","CR63836275771236836730",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Antonio","Sabo","68433302","207920609","CR63836275771236836730", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Rosa","Eckhardt",92765146,"109020442","CR94595171174609018806",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Rosa","Eckhardt","92765146","109020442","CR94595171174609018806", 0 , "2022-01-01 09:00:00", 0), 256));
insert into Copero(nombre,apellido,telefono, cedula, cuentaBancaria, totalDinero, fechaUltimoPago, deleted, checkSum) values("Erica","Davidson",56705274,"201090984","CR70485167467435513454",0 ,"2022-01-01 09:00:00" ,0, SHA2(CONCAT("Erica","Davidson","56705274","201090984","CR70485167467435513454", 0 , "2022-01-01 09:00:00", 0), 256));

insert into Clientes(nombre,apellido,telefono, createdAT) values("Merle","Moser",44211316,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("David","Freeders",15276725,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Charles","Carpio",22383978,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Kathy","Brown",98447780,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Lise","Barnhurst",97719170,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jennifer","Richardson",99603965,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Darline","Holton",47957620,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Thomas","Nikolai",14505549,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Judy","Lewis",63842765,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Ruben","Larsen",33202904,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Heather","Bisard",43237054,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Walter","Murphy",13974926,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Lawrence","Hirkaler",26538024,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Benjamin","Meisner",60108092,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("John","Alber",47398977,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Pablo","Hughes",93429050,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Joann","Newport",65994903,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jean","Allen",58974726,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Ronald","Milliken",89964741,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Tiffany","Geathers",89235362,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Enrique","Cherry",57878865,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Nicole","Almon",40378979,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jose","Martinez",18758058,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Victor","Lujan",99124940,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Richard","Tracy",63559977,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Laura","Obrien",43032850,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("William","Tocco",89148960,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Curtis","Thomas",63441019,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jamie","Stockman",25383607,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Marjorie","Hinton",65217768,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Michael","Rosner",12933069,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("William","Lake",71139080,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Mark","Parenteau",20116322,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Ray","Lange",98424015,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Walter","Long",82719386,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Arthur","Danna",11305190,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Deon","Devlin",60974638,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Christopher","Gonzalez",10344156,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Deborah","Middleton",47467811,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Alison","Roberson",55461580,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Thomas","Allen",71488753,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Tracey","Walker",26503906,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Robert","Avant",26802973,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Maria","Pentz",46756857,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Ruthie","Stokes",66916953,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Darwin","Knight",68253489,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Van","Young",74749574,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Peggy","Phillips",55342691,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jason","Martin",51897244,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Laura","Williams",74537555,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Clifford","Benson",70469264,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Carlos","Ladner",20515272,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Dana","Graves",33539386,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Vanessa","Bertran",32784771,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Ethan","Gutierrez",83973305,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Mary","Card",56128988,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Anthony","Steele",23184433,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Robert","Slayton",80895059,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Arthur","Hughes",38758707,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Eileen","Luciano",46907879,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Laura","Davis",26434194,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Theodore","Casanova",97854959,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Henrietta","Grubb",68167306,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Amy","Kaiser",27248765,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Donald","Mills",92293470,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Ann","Maisano",96118503,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Tammy","Ward",84817236,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Cleta","Zimmerman",70937879,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Brandon","Wright",45274504,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Eric","Harvey",89598619,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Glenda","Beck",26364982,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Kathy","Kline",87905332,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Joshua","Hoffman",38146198,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Eric","Peters",92534672,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Andrew","Baker",30729578,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Stephen","Binion",46361130,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Mary","Birch",42962011,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Latonia","Mccann",10781231,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Roscoe","Todd",56475314,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Brittany","Cooney",24585815,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Carolyn","Kempton",32934009,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jeffrey","Farley",23542580,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Angela","Hanson",51246959,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Arlene","Mccain",46373101,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Carmen","Lindstrom",20466638,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Nicole","Sacco",48015489,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Emily","Hurley",33594739,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Rosie","Elliott",66944786,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Deanna","Rios",52773731,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Catherine","Mullin",89646138,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Matthew","Thomas",66868697,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Brandon","Oubre",32985294,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Peter","Guerrero",49485328,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Eileen","Whitman",12639546,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jennifer","Washington",90963510,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Martin","Berry",20931677,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Vicky","Horner",90919767,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("David","Smudrick",14878156,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Benjamin","Weidert",18279168,"2022-01-01 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Robert","Herrod",90393302,"2022-01-01 09:00:00");

insert into Clientes(nombre,apellido,telefono, createdAT) values("Stephanie","Gordon",96936205,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Nellie","Delaney",88347033,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Joan","Patino",30735151,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Doris","Tillman",20959089,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Nellie","Meckes",86199598,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Sara","Washington",63099015,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Michael","Dowlin",58245219,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Rhonda","Gaston",27503346,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Lawrence","Ramos",52636378,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Brian","Hendriks",20317648,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Celia","Overlock",24043329,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Demetrius","Miller",43666477,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Steven","Davis",22309910,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Kayla","Brandt",94541185,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Darlene","Alward",92871257,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("William","Morefield",73104856,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Adriana","Coleman",39254629,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Alta","Harland",38265023,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Rose","Voyles",59684562,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Russell","Hoskins",95315514,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Susana","Foster",44227025,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Kelly","Mcadory",60794772,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Dora","Myers",14871148,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Dorothy","Harrington",23718101,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Colleen","Guizar",67145000,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Clifford","Willner",65302838,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Emma","Perkins",16618386,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jonathan","Books",42705319,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Mary","Hernandez",76605122,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Susan","Buckner",80009153,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jeffrey","Cooper",29491319,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Hilda","Guardado",47083977,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jerry","Chamness",67239295,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Lillian","Sayers",95019348,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Mercedes","Perez",16825249,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Clara","Perry",82351711,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Vincent","Evans",48514664,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Matthew","Daniels",77393843,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("William","Watkins",20729802,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Doris","Dotson",93178729,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Joan","Mateo",24517947,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Neil","Kuykendall",56032015,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("James","Dipiano",60718114,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Misty","Perez",36123664,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Allen","Park",13814402,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Mallory","Hanna",16539157,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Dexter","Kowalski",40078928,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Edna","Moore",74379510,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Ronnie","Martin",35671907,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Calvin","Pittman",61908200,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Edward","Melton",48535055,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("George","Sullivan",60291374,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Joseph","Chapple",82818229,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jose","Sankey",47694476,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("John","Christensen",18366436,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Allan","Butler",78555901,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Lorena","Lavigne",78505973,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Robert","Dugue",81058577,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("William","Kerber",10828056,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jessica","Tomblin",32313255,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Paul","Russell",76334780,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jean","Carsey",78928553,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Melissa","Mcghee",92943955,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Claire","Hernandez",31874896,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Mary","Odom",17805248,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Paul","Leach",68493105,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Virginia","Hollyday",58059362,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Tracy","Acosta",47654171,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("James","Domingo",79835148,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Lavon","Troiano",75405047,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Richard","Brown",85707817,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Kenneth","Barringer",66399082,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Lottie","Scavuzzo",27917904,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Beau","Heckert",71705938,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Christine","Murphy",48754980,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Timothy","Chavez",45081556,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Russell","Cochran",38427332,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Wendy","Pompi",33665511,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Hugh","Cramer",43484918,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Eugenia","Mccracken",82238672,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Hilary","Turner",43062060,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Deanna","Foronda",59024992,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Suzanne","Mclaren",96321975,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Renata","Kolter",72511262,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Andrea","Bengtson",42199459,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Patty","Buenrostro",69774241,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Donald","Hebert",31877732,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Brian","Anderson",56878978,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Vicki","Mapp",81431442,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Sharon","Bourbon",95252466,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Margaret","Rodrigez",44192637,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Brian","Schwartz",98183410,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Katherine","Noble",20295066,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Charlie","Willey",73551446,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Lawrence","Gilmore",95964354,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Brittany","Allen",43626172,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Steve","Kelley",60601522,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Ronnie","Davidson",70483776,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Margaret","Catalano",93507534,"2022-01-02 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jody","Rivas",49555839,"2022-01-02 09:00:00");

insert into Clientes(nombre,apellido,telefono, createdAT) values("Jessie","Mcandrew",19103688,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Terri","Hartman",58966300,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Cody","Taylor",46955589,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("James","Mcadams",58149020,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Malcolm","Harper",61118062,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Joshua","Fry",36998720,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Nelson","Cattaneo",27305832,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Eric","Peters",49156299,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Bradley","Sterling",31144592,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Patricia","Allison",81015711,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Marisa","Perez",64656952,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Rose","Moody",40515574,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Parker","Barnes",50583064,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Wanda","Markell",13902474,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Carmen","Schmid",48268515,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Nadine","Nichols",48231395,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Christopher","Sule",13075592,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Natasha","Wade",92865059,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Felicia","Williams",56745148,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Gordon","Montoya",84991121,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Alexis","Anderson",89324654,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Andrea","Leon",23993666,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("John","Lamon",31731928,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Annie","Brown",65491234,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Keith","Small",65256165,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Melissa","Weyrick",87697150,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Courtney","Grabner",81701253,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Donald","Carlson",43108227,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Margarita","Meyer",29424804,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Deanna","Jubilee",59201192,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Frank","Credle",31439979,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Dale","Guerin",70002116,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Christopher","Cole",20835395,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Juanita","Kirk",85235690,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Tyron","Hershenson",47559404,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Micheal","Shull",74174666,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Linda","Hartly",56197285,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Lisa","Redenbaugh",69179922,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Albert","Yoes",52057165,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Abigail","Boggioni",44108912,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Willie","Aromin",45733323,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Celia","Kim",23313169,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Tabitha","Hanson",27494390,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Amy","Parker",11214657,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Leticia","Grove",65889331,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Elizabeth","Cisneros",29133319,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Joshua","Moore",66352333,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Lionel","Suh",74936958,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Eric","Brewster",89415715,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Justin","Smith",67335506,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Paula","Hegmann",42312237,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Daniel","Murphy",23438105,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Terri","Holt",56998475,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Lawrence","Nasta",50757482,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("George","Hooks",79252017,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Erin","Oneal",29523824,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Doris","Miller",48351485,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jimmy","Matos",39954343,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Willie","Kaminski",60227741,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Sibyl","Cole",89333926,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Nicole","Ramirez",72402018,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Mary","Huffman",86577891,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Craig","Dean",56923760,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Lillian","Schenkel",95842654,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Caitlin","Rodibaugh",35954439,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Richard","Criswell",76365275,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("John","Young",15543153,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Helen","Jones",86085577,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("James","Boyd",73756033,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Corrie","Evans",76068483,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Glenda","Thornberg",25132672,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Brandie","Frank",95772984,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Shawn","Curtis",49223141,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Steven","Bryant",88481113,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Gloria","Dixon",30323840,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jacob","Kirschner",41251324,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Roy","Padilla",44224553,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Edna","Benack",56394895,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Lai","Valdovinos",14749085,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Sabrina","Miller",66685473,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("David","Thompson",18338943,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Gerald","Chase",71972807,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Jonathan","Jones",33657097,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Alison","Wilson",99849402,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Dallas","Mcgovern",11033036,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Mary","Molinaro",13297423,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Stephanie","Laws",12374318,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Daniel","Lee",53027778,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Barbara","Loffler",75573063,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Brittany","Klein",98411412,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Dennis","Snodgrass",89534380,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Summer","Jackson",50499140,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Brian","Hannah",66654632,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("August","Lopez",23097327,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Nathaniel","Pinon",53426885,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Eric","Cavender",92307780,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Andrea","Cahoon",99428692,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Gary","Stinson",67581336,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Katherine","Smith",74851753,"2022-01-03 09:00:00");
insert into Clientes(nombre,apellido,telefono, createdAT) values("Shamika","Nelson",97816384,"2022-01-03 09:00:00");


        
INSERT INTO turnos (horaInicio, horaFinal) VALUES
('08:00:00', '12:00:00'),
('12:00:00', '16:00:00'),
('16:00:00', '20:00:00');

set @fechaInicial = '2022-01-01 09:00:00';

Insert INTO UnidadesMedida(nombre) VALUES("Mililitro");
Insert INTO UnidadesMedida(nombre) VALUES("Litro");
Insert INTO UnidadesMedida(nombre) VALUES("Gramo");
Insert INTO UnidadesMedida(nombre) VALUES("Kilogramo");
Insert INTO UnidadesMedida(nombre) VALUES("Hojas");
Insert INTO UnidadesMedida(nombre) VALUES("Unidad");

INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Sirope Cola", 1,1,800.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Sirope Chicle", 1,1,800.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Leche en Polvo", 3, 1 ,5670.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Leche condensada", 3,1,1230.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Hielo Molido", 3,1,8000.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Helado", 3,1,20380.20, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Ron Blanco", 1,1,10030.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Jugo de piña", 1,1,1320.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Leche de coco", 1,1,1900.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Jugo de limon", 1,1,1690.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Azucar", 3,1,1530.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Vodka", 1,1,8160.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Jugo de melocoton", 1,1,2880.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Jugo de arandano", 1,1,3550.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Jugo de naranja", 1,1,1800.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Tequila", 1,1,16730.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Triple seco", 1,1,8190.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Sal", 3,1,420.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Hierbabuena", 5,1,500.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Limon", 6,1,200.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Soda", 1,1,1520.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Amareto", 1,1,13790.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Baileys", 1,1,18830.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Kahlua", 1,1,15280.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Cachaza", 1,1,14560.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Azucar morena", 3,1,1780.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Cacique", 1,1,4990.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Jugo de tomate", 1,1,1140.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Pimienta", 3,1,4420.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Tabasco", 1,1,2700.00, @fechaInicial);
INSERT INTO Ingredientes(nombre, idUnidadeMedida, enabled, precio, fechaCompra) 
VALUES("Salsa Lizano", 1,1,3200.00, @fechaInicial);


INSERT INTO Productos(nombre, enabled) VALUES("Copo de cola",1);
INSERT INTO Productos(nombre, enabled) VALUES("Copo de chicle",1);
INSERT INTO Productos(nombre, enabled) VALUES("Churchill",1);
INSERT INTO Productos(nombre, enabled) VALUES("Piña Colada",1);
INSERT INTO Productos(nombre, enabled) VALUES("Daikirí",1);
INSERT INTO Productos(nombre, enabled) VALUES("Sexo en la playa",1);
INSERT INTO Productos(nombre, enabled) VALUES("Margarita",1);
INSERT INTO Productos(nombre, enabled) VALUES("Mojito",1);
INSERT INTO Productos(nombre, enabled) VALUES("Mamadita",1);
INSERT INTO Productos(nombre, enabled) VALUES("Caipirinha",1);
INSERT INTO Productos(nombre, enabled) VALUES("Chiliguaro",1);



INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(1, 1, 60);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(3, 1, 15);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(5, 1, 200);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(4, 1, 30);

INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(2, 2, 60);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(3, 2, 15);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(5, 2, 200);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(4, 2, 30);

INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(1, 3, 60);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(3, 3, 15);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(5, 3, 200);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(4, 3, 30);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(6, 3, 20);

INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(7, 4, 100);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(8, 4, 250);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(9, 4, 150);

INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(7, 5, 50);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(10, 5, 25);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(11, 5, 8);

INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(12, 6, 40);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(13, 6, 20);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(14, 6, 40);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(15, 6, 40);


INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(16, 7, 50);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(17, 7, 25);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(10, 7, 25);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(18, 7, 8);

INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(11, 8, 16);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(19, 8, 8);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(10, 8, 30);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(7, 8, 60);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(20, 8, 0.5);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(21, 8, 120);

INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(22, 9, 15);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(23, 9, 15);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(24, 9, 15);

INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(20, 10, 2);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(26, 10, 30);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(25, 10, 60);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(10, 10, 15);

INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(28, 11, 30);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(27, 11, 15);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(30, 11, 5);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(29, 11, 5);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(10, 11, 5);
INSERT INTO ingredientesxproductos (idingrediente, idproducto, cantidad) values 
(31, 11, 5);


INSERT INTO LogPrecios(valor, fechaInicio, active, createdAT, updateAT, checkSum, idProducto)
VALUES(1000.00,@fechaInicial,1,@fechaInicial, @fechaInicial,
		SHA2(CONCAT(1000.00,@fechaInicial,1,@fechaInicial,1), 256),
		1);

INSERT INTO LogPrecios(valor, fechaInicio, active, createdAT, updateAT, checkSum, idProducto)
VALUES(1000.00,@fechaInicial,1,@fechaInicial, @fechaInicial,
		SHA2(CONCAT(1000.00,@fechaInicial,1,@fechaInicial,2), 256),
		2);

INSERT INTO LogPrecios(valor, fechaInicio, active, createdAT, updateAT, checkSum, idProducto)
VALUES(2000.00,@fechaInicial,1,@fechaInicial, @fechaInicial,
		SHA2(CONCAT(2000.00,@fechaInicial,1,@fechaInicial,3), 256),
		3);
        
INSERT INTO LogPrecios(valor, fechaInicio, active, createdAT, updateAT, checkSum, idProducto)
VALUES(2500.00,@fechaInicial,1,@fechaInicial, @fechaInicial,
		SHA2(CONCAT(2500.00,@fechaInicial,1,@fechaInicial,4), 256),
		4);
        
INSERT INTO LogPrecios(valor, fechaInicio, active, createdAT, updateAT, checkSum, idProducto)
VALUES(2500.00,@fechaInicial,1,@fechaInicial, @fechaInicial,
		SHA2(CONCAT(2500.00,@fechaInicial,1,@fechaInicial,5), 256),
		5);
        
INSERT INTO LogPrecios(valor, fechaInicio, active, createdAT, updateAT, checkSum, idProducto)
VALUES(2500.00,@fechaInicial,1,@fechaInicial, @fechaInicial,
		SHA2(CONCAT(2500.00,@fechaInicial,1,@fechaInicial,6), 256),
		6);
        
INSERT INTO LogPrecios(valor, fechaInicio, active, createdAT, updateAT, checkSum, idProducto)
VALUES(2000.00,@fechaInicial,1,@fechaInicial, @fechaInicial,
		SHA2(CONCAT(2000.00,@fechaInicial,1,@fechaInicial,7), 256),
		7);
        
INSERT INTO LogPrecios(valor, fechaInicio, active, createdAT, updateAT, checkSum, idProducto)
VALUES(2500.00,@fechaInicial,1,@fechaInicial, @fechaInicial,
		SHA2(CONCAT(2500.00,@fechaInicial,1,@fechaInicial,8), 256),
		8);

INSERT INTO LogPrecios(valor, fechaInicio, active, createdAT, updateAT, checkSum, idProducto)
VALUES(3000.00,@fechaInicial,1,@fechaInicial, @fechaInicial,
		SHA2(CONCAT(3000.00,@fechaInicial,1,@fechaInicial,9), 256),
		9);

INSERT INTO LogPrecios(valor, fechaInicio, active, createdAT, updateAT, checkSum, idProducto)
VALUES(2500.00,@fechaInicial,1,@fechaInicial, @fechaInicial,
		SHA2(CONCAT(2500.00,@fechaInicial,1,@fechaInicial,10), 256),
		10);
        
INSERT INTO LogPrecios(valor, fechaInicio, active, createdAT, updateAT, checkSum, idProducto)
VALUES(1800.00,@fechaInicial,1,@fechaInicial, @fechaInicial,
		SHA2(CONCAT(2500.00,@fechaInicial,1,@fechaInicial,11), 256),
		11);

insert into comisioneslogs (porcentaje, enabled, fechaInicio, checkSum) values
(9.00, 1, '2022-01-01 09:00:00', SHA2(CONCAT(9.00, '2022-01-01 09:00:00', 1 ), 256));


insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(1,1,1,'2022-01-01 08:00:00',1000.00,0,SHA2(CONCAT(1,1,1,'2022-01-01 08:00:00',1000.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(2,1,1,'2022-01-01 08:00:00',1000.00,0,SHA2(CONCAT(2,1,1,'2022-01-01 08:00:00',1000.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(3,1,1,'2022-01-01 08:00:00',800.00,0,SHA2(CONCAT(3,1,1,'2022-01-01 08:00:00',800.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(4,1,1,'2022-01-01 08:00:00',397.00,0,SHA2(CONCAT(4,1,1,'2022-01-01 08:00:00',397.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(5,1,1,'2022-01-01 08:00:00',20000.00,0,SHA2(CONCAT(5,1,1,'2022-01-01 08:00:00',20000.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(6,1,1,'2022-01-01 08:00:00',5300.00,0,SHA2(CONCAT(6,1,1,'2022-01-01 08:00:00',5300.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(7,1,1,'2022-01-01 08:00:00',750.00,0,SHA2(CONCAT(7,1,1,'2022-01-01 08:00:00',750.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(8,1,1,'2022-01-01 08:00:00',1000.00,0,SHA2(CONCAT(8,1,1,'2022-01-01 08:00:00',1000.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(9,1,1,'2022-01-01 08:00:00',400.00,0,SHA2(CONCAT(9,1,1,'2022-01-01 08:00:00',400.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(10,1,1,'2022-01-01 08:00:00',350.00,0,SHA2(CONCAT(10,1,1,'2022-01-01 08:00:00',350.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(11,1,1,'2022-01-01 08:00:00',2000.00,0,SHA2(CONCAT(11,1,1,'2022-01-01 08:00:00',2000.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(12,1,1,'2022-01-01 08:00:00',1000.00,0,SHA2(CONCAT(12,1,1,'2022-01-01 08:00:00',1000.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(13,1,1,'2022-01-01 08:00:00',1890.00,0,SHA2(CONCAT(13,1,1,'2022-01-01 08:00:00',1890.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(14,1,1,'2022-01-01 08:00:00',1890.00,0,SHA2(CONCAT(14,1,1,'2022-01-01 08:00:00',1890.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(15,1,1,'2022-01-01 08:00:00',2200.00,0,SHA2(CONCAT(15,1,1,'2022-01-01 08:00:00',2200.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(16,1,1,'2022-01-01 08:00:00',750.00,0,SHA2(CONCAT(16,1,1,'2022-01-01 08:00:00',750.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(17,1,1,'2022-01-01 08:00:00',1000.00,0,SHA2(CONCAT(17,1,1,'2022-01-01 08:00:00',1000.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(18,1,1,'2022-01-01 08:00:00',500.00,0,SHA2(CONCAT(18,1,1,'2022-01-01 08:00:00',500.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(19,1,1,'2022-01-01 08:00:00',100.00,0,SHA2(CONCAT(19,1,1,'2022-01-01 08:00:00',100.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(20,1,1,'2022-01-01 08:00:00',1.00,0,SHA2(CONCAT(20,1,1,'2022-01-01 08:00:00',1.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(21,1,1,'2022-01-01 08:00:00',2000.00,0,SHA2(CONCAT(21,1,1,'2022-01-01 08:00:00',2000.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(22,1,1,'2022-01-01 08:00:00',500.00,0,SHA2(CONCAT(22,1,1,'2022-01-01 08:00:00',500.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(23,1,1,'2022-01-01 08:00:00',1000.00,0,SHA2(CONCAT(23,1,1,'2022-01-01 08:00:00',1000.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(24,1,1,'2022-01-01 08:00:00',750.00,0,SHA2(CONCAT(24,1,1,'2022-01-01 08:00:00',750.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(25,1,1,'2022-01-01 08:00:00',970.00,0,SHA2(CONCAT(25,1,1,'2022-01-01 08:00:00',970.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(26,1,1,'2022-01-01 08:00:00',2000.00,0,SHA2(CONCAT(26,1,1,'2022-01-01 08:00:00',2000.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(27,1,1,'2022-01-01 08:00:00',1000.00,0,SHA2(CONCAT(27,1,1,'2022-01-01 08:00:00',1000.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(28,1,1,'2022-01-01 08:00:00',1000.00,0,SHA2(CONCAT(28,1,1,'2022-01-01 08:00:00',1000.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(29,1,1,'2022-01-01 08:00:00',350.00,0,SHA2(CONCAT(29,1,1,'2022-01-01 08:00:00',350.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(30,1,1,'2022-01-01 08:00:00',250.00,0,SHA2(CONCAT(30,1,1,'2022-01-01 08:00:00',250.00,0,"feliz navidad"), 256));
insert into inventariocarrito(idIngrediente, idCarrito, idCoperoResponsable, fecha, cantidad, tipoOperacion,checkSum) values
(31,1,1,'2022-01-01 08:00:00',1000.00,0,SHA2(CONCAT(31,1,1,'2022-01-01 08:00:00',1000.00,0,"feliz navidad"), 256));
# tipoOperacion ==> 0 = Producto Nuevo | 1 = Venta | 2 = Refill | 3 = Producto Caducado


INSERT INTO EstadoSolicitud(estado)VALUES
("Aceptado"),
("Rechazado"),
("Cancelado"),
("Pendiente"),
("Finalizado");



INSERT INTO PrecioProductoXplaya(valor, fechaInicio, active, createdAT, updatedAT, checkSum, idProducto, idPlaya)
VALUES(2500.00,@fechaInicial,1,@fechaInicial, @fechaInicial,
		SHA2(CONCAT(2500.00,@fechaInicial,1,@fechaInicial,9), 256),
		9,3);
delete from PrecioProductoXplaya where idPrecioProductoXplaya

SELECT Productos.idProducto,nombre,valor FROM Productos
INNER JOIN LogPrecios ON Productos.idProducto = LogPrecios.idProducto
ORDER BY valor DESC;

