-- MySQL Script generated by MySQL Workbench
-- Thu Mar 23 01:57:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Caso2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Caso2` ;

-- -----------------------------------------------------
-- Schema Caso2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Caso2` DEFAULT CHARACTER SET utf8 ;
USE `Caso2` ;

-- -----------------------------------------------------
-- Table `Caso2`.`Copero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Copero` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Copero` (
  `idCopero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `telefono` INT UNSIGNED NOT NULL,
  `cedula` VARCHAR(20) NOT NULL,
  `cuentaBancaria` VARCHAR(22) NOT NULL,
  `totalDinero` DECIMAL(11,2) NOT NULL DEFAULT 0,
  `fechaUltimoPago` DATETIME NOT NULL,
  `deleted` BIT NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  PRIMARY KEY (`idCopero`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Carrito` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Carrito` (
  `idCarrito` SMALLINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(10) NOT NULL,
  `enabled` BIT NOT NULL,
  PRIMARY KEY (`idCarrito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Playas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Playas` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Playas` (
  `idPlaya` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idPlaya`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`ComisionesLogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`ComisionesLogs` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`ComisionesLogs` (
  `idComisionLog` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `porcentaje` DECIMAL(5,2) NOT NULL,
  `enabled` BIT NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFinal` DATETIME NULL,
  PRIMARY KEY (`idComisionLog`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Ventas` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Ventas` (
  `idVenta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPlaya` SMALLINT UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL,
  `idComisionLog` INT UNSIGNED NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  `idCopero` INT UNSIGNED NOT NULL,
  `deleted` BIT NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  `pago` DECIMAL(10,2) NOT NULL,
  `vuelto` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idVenta`, `idPlaya`, `idComisionLog`, `idCopero`),
  INDEX `fk_Ventas_Playas1_idx` (`idPlaya` ASC) VISIBLE,
  INDEX `fk_Ventas_Comisiones1_idx` (`idComisionLog` ASC) VISIBLE,
  INDEX `fk_Ventas_Copero1_idx` (`idCopero` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Playas1`
    FOREIGN KEY (`idPlaya`)
    REFERENCES `Caso2`.`Playas` (`idPlaya`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Comisiones1`
    FOREIGN KEY (`idComisionLog`)
    REFERENCES `Caso2`.`ComisionesLogs` (`idComisionLog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Copero1`
    FOREIGN KEY (`idCopero`)
    REFERENCES `Caso2`.`Copero` (`idCopero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Caso2`.`UnidadesMedida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`UnidadesMedida` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`UnidadesMedida` (
  `idUnidadeMedida` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idUnidadeMedida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Ingredientes` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Ingredientes` (
  `idIngrediente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `idUnidadeMedida` TINYINT UNSIGNED NOT NULL,
  `enabled` BIT NOT NULL,
  `precio` DECIMAL(8,2) NOT NULL,
  `fechaCompra` DATETIME NOT NULL,
  PRIMARY KEY (`idIngrediente`),
  INDEX `fk_Ingredientes_UnidadesMedida1_idx` (`idUnidadeMedida` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredientes_UnidadesMedida1`
    FOREIGN KEY (`idUnidadeMedida`)
    REFERENCES `Caso2`.`UnidadesMedida` (`idUnidadeMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Turnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Turnos` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Turnos` (
  `idTurno` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `horaInicio` TIME NOT NULL,
  `horaFinal` TIME NOT NULL,
  PRIMARY KEY (`idTurno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Reportes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Reportes` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Reportes` (
  `idReporte` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idCopero` INT UNSIGNED NOT NULL,
  `idCarrito` SMALLINT(4) UNSIGNED NOT NULL,
  `idTurno` SMALLINT UNSIGNED NOT NULL,
  `fecha` DATE NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  PRIMARY KEY (`idReporte`),
  INDEX `fk_Reportes_Copero1_idx` (`idCopero` ASC) VISIBLE,
  INDEX `fk_Reportes_Carrito1_idx` (`idCarrito` ASC) VISIBLE,
  INDEX `fk_Reportes_Turnos1_idx` (`idTurno` ASC) VISIBLE,
  CONSTRAINT `fk_Reportes_Copero1`
    FOREIGN KEY (`idCopero`)
    REFERENCES `Caso2`.`Copero` (`idCopero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reportes_Carrito1`
    FOREIGN KEY (`idCarrito`)
    REFERENCES `Caso2`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reportes_Turnos1`
    FOREIGN KEY (`idTurno`)
    REFERENCES `Caso2`.`Turnos` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Productos` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Productos` (
  `idProducto` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  `enabled` BIT NOT NULL,
  `comentario` VARCHAR(500) NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`IngredientesXproductos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`IngredientesXproductos` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`IngredientesXproductos` (
  `idIngrediente` INT UNSIGNED NOT NULL,
  `idProducto` SMALLINT UNSIGNED NOT NULL,
  `cantidad` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`idIngrediente`, `idProducto`),
  INDEX `fk_Ingredientes_has_Productos_Productos1_idx` (`idProducto` ASC) VISIBLE,
  INDEX `fk_Ingredientes_has_Productos_Ingredientes1_idx` (`idIngrediente` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredientes_has_Productos_Ingredientes1`
    FOREIGN KEY (`idIngrediente`)
    REFERENCES `Caso2`.`Ingredientes` (`idIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredientes_has_Productos_Productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Caso2`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`InventarioCarrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`InventarioCarrito` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`InventarioCarrito` (
  `idIngrediente` INT UNSIGNED NOT NULL,
  `idCarrito` SMALLINT(4) UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT NOW(),
  `checkSum` VARBINARY(150) NOT NULL,
  `cantidad` DECIMAL(10,4) NOT NULL,
  `idCoperoResponsable` INT UNSIGNED NOT NULL,
  `tipoOperacion` TINYINT UNSIGNED NOT NULL COMMENT '0 = Producto Nuevo\n1 = Venta\n2 = Refill\n3= Producto Caducado\n',
  PRIMARY KEY (`idIngrediente`, `idCarrito`, `idCoperoResponsable`),
  INDEX `fk_Ingredientes_has_Carrito_Carrito1_idx` (`idCarrito` ASC) VISIBLE,
  INDEX `fk_Ingredientes_has_Carrito_Ingredientes1_idx` (`idIngrediente` ASC) VISIBLE,
  INDEX `fk_InventarioCarrito_Copero1_idx` (`idCoperoResponsable` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredientes_has_Carrito_Ingredientes1`
    FOREIGN KEY (`idIngrediente`)
    REFERENCES `Caso2`.`Ingredientes` (`idIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredientes_has_Carrito_Carrito1`
    FOREIGN KEY (`idCarrito`)
    REFERENCES `Caso2`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InventarioCarrito_Copero1`
    FOREIGN KEY (`idCoperoResponsable`)
    REFERENCES `Caso2`.`Copero` (`idCopero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`ProductosXventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`ProductosXventas` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`ProductosXventas` (
  `idProducto` SMALLINT UNSIGNED NOT NULL,
  `idVenta` INT UNSIGNED NOT NULL,
  `cantidad` SMALLINT ZEROFILL NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  PRIMARY KEY (`idProducto`, `idVenta`),
  INDEX `fk_Productos_has_Ventas_Ventas1_idx` (`idVenta` ASC) VISIBLE,
  INDEX `fk_Productos_has_Ventas_Productos1_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_has_Ventas_Productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Caso2`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Ventas_Ventas1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `Caso2`.`Ventas` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Clientes` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `createdAT` DATETIME NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`SolicitudesWeb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`SolicitudesWeb` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`SolicitudesWeb` (
  `idSolicitudWeb` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idCliente` INT UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL,
  `ubicacion` POINT NOT NULL,
  `señasDireccion` VARCHAR(500) NULL,
  `idPlaya` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idSolicitudWeb`, `idCliente`, `idPlaya`),
  INDEX `fk_SolicitudesWeb_Clientes1_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_SolicitudesWeb_Playas1_idx` (`idPlaya` ASC) VISIBLE,
  CONSTRAINT `fk_SolicitudesWeb_Clientes1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Caso2`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolicitudesWeb_Playas1`
    FOREIGN KEY (`idPlaya`)
    REFERENCES `Caso2`.`Playas` (`idPlaya`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`ProductosXSolicitudesWeb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`ProductosXSolicitudesWeb` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`ProductosXSolicitudesWeb` (
  `idProducto` SMALLINT UNSIGNED NOT NULL,
  `cantidad` DECIMAL(8,2) NOT NULL,
  `idSolicitudWeb` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idProducto`, `idSolicitudWeb`),
  INDEX `fk_Productos_has_SolicitudesWeb_Productos1_idx` (`idProducto` ASC) VISIBLE,
  INDEX `fk_ProductosXSolicitudesWeb_SolicitudesWeb1_idx` (`idSolicitudWeb` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_has_SolicitudesWeb_Productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Caso2`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductosXSolicitudesWeb_SolicitudesWeb1`
    FOREIGN KEY (`idSolicitudWeb`)
    REFERENCES `Caso2`.`SolicitudesWeb` (`idSolicitudWeb`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`LogPrecios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`LogPrecios` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`LogPrecios` (
  `idLogPrecio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(9,2) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFinal` DATETIME NULL,
  `active` BIT NOT NULL,
  `createdAT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `checkSum` VARBINARY(150) NOT NULL,
  `idProducto` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idLogPrecio`, `idProducto`),
  INDEX `fk_LogPrecios_Productos1_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_LogPrecios_Productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Caso2`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`PrecioProductoXplaya`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`PrecioProductoXplaya` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`PrecioProductoXplaya` (
  `idPlaya` SMALLINT UNSIGNED NOT NULL,
  `valor` DECIMAL(9,2) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFinal` DATETIME NULL,
  `active` BIT NOT NULL,
  `createdAT` TIMESTAMP NOT NULL,
  `updatedAT` TIMESTAMP NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  `idProducto` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPlaya`, `idProducto`),
  INDEX `fk_Playas_has_LogPrecios_Playas1_idx` (`idPlaya` ASC) VISIBLE,
  INDEX `fk_PrecioProductoXplaya_Productos1_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Playas_has_LogPrecios_Playas1`
    FOREIGN KEY (`idPlaya`)
    REFERENCES `Caso2`.`Playas` (`idPlaya`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PrecioProductoXplaya_Productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Caso2`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`ReportesXcajas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`ReportesXcajas` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`ReportesXcajas` (
  `idCajaDineroLog` INT UNSIGNED NOT NULL,
  `idReporte` INT UNSIGNED NOT NULL,
  `idCoperoRecibe` INT UNSIGNED NOT NULL,
  `isAgree` BIT NOT NULL,
  `dinero` DECIMAL(11,2) NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  PRIMARY KEY (`idCajaDineroLog`, `idReporte`, `idCoperoRecibe`),
  INDEX `fk_CajaDineroLogs_has_Reportes_Reportes1_idx` (`idReporte` ASC) VISIBLE,
  INDEX `fk_ReportesXcajas_Copero1_idx` (`idCoperoRecibe` ASC) VISIBLE,
  CONSTRAINT `fk_CajaDineroLogs_has_Reportes_Reportes1`
    FOREIGN KEY (`idReporte`)
    REFERENCES `Caso2`.`Reportes` (`idReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReportesXcajas_Copero1`
    FOREIGN KEY (`idCoperoRecibe`)
    REFERENCES `Caso2`.`Copero` (`idCopero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`EstadoSolicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`EstadoSolicitud` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`EstadoSolicitud` (
  `idEstadoSolicitud` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEstadoSolicitud`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`SolicitudesLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`SolicitudesLog` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`SolicitudesLog` (
  `idEstadoSolicitud` INT UNSIGNED NOT NULL,
  `idSolicitudWeb` INT UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  PRIMARY KEY (`idEstadoSolicitud`, `idSolicitudWeb`),
  INDEX `fk_EstadoSolicitud_has_SolicitudesWeb_SolicitudesWeb1_idx` (`idSolicitudWeb` ASC) VISIBLE,
  INDEX `fk_EstadoSolicitud_has_SolicitudesWeb_EstadoSolicitud1_idx` (`idEstadoSolicitud` ASC) VISIBLE,
  CONSTRAINT `fk_EstadoSolicitud_has_SolicitudesWeb_EstadoSolicitud1`
    FOREIGN KEY (`idEstadoSolicitud`)
    REFERENCES `Caso2`.`EstadoSolicitud` (`idEstadoSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EstadoSolicitud_has_SolicitudesWeb_SolicitudesWeb1`
    FOREIGN KEY (`idSolicitudWeb`)
    REFERENCES `Caso2`.`SolicitudesWeb` (`idSolicitudWeb`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`TipoOperacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`TipoOperacion` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`TipoOperacion` (
  `idTipoOperacion` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idTipoOperacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`TipoEvento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`TipoEvento` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`TipoEvento` (
  `idTipoEvento` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Sources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Sources` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Sources` (
  `idSource` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idSource`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Levels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Levels` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Levels` (
  `idLevel` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idLevel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Caso2`.`Bitacora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Caso2`.`Bitacora` ;

CREATE TABLE IF NOT EXISTS `Caso2`.`Bitacora` (
  `idBitacora` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user` VARCHAR(40) NOT NULL,
  `idTipoOperacion` SMALLINT UNSIGNED NOT NULL,
  `idTipoEvento` SMALLINT UNSIGNED NOT NULL,
  `checkSum` VARBINARY(150) NOT NULL,
  `idSource` SMALLINT UNSIGNED NOT NULL,
  `idLevel` TINYINT UNSIGNED NOT NULL,
  `computer` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `referenceid1` BIGINT NOT NULL,
  `referenceid2` BIGINT NULL,
  `value1` VARCHAR(60) NOT NULL,
  `value2` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idBitacora`, `idTipoOperacion`, `idTipoEvento`, `idSource`, `idLevel`),
  INDEX `fk_Bitacora_TipoOperacion1_idx` (`idTipoOperacion` ASC) VISIBLE,
  INDEX `fk_Bitacora_TipoEvento1_idx` (`idTipoEvento` ASC) VISIBLE,
  INDEX `fk_Bitacora_Sources1_idx` (`idSource` ASC) VISIBLE,
  INDEX `fk_Bitacora_Levels1_idx` (`idLevel` ASC) VISIBLE,
  CONSTRAINT `fk_Bitacora_TipoOperacion1`
    FOREIGN KEY (`idTipoOperacion`)
    REFERENCES `Caso2`.`TipoOperacion` (`idTipoOperacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bitacora_TipoEvento1`
    FOREIGN KEY (`idTipoEvento`)
    REFERENCES `Caso2`.`TipoEvento` (`idTipoEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bitacora_Sources1`
    FOREIGN KEY (`idSource`)
    REFERENCES `Caso2`.`Sources` (`idSource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bitacora_Levels1`
    FOREIGN KEY (`idLevel`)
    REFERENCES `Caso2`.`Levels` (`idLevel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
